### PR TITLE
Feature/28 Added auth module and user logic

### PR DESCRIPTION
**Pull request by gonzcm**
## Description
Added auth module and user creation

## Related Issue(s)
- #28 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @jmartinacu 
- @alvgonfri 

## Notes
You can test the functionality from swagger, by clicking on the "authorize" button and entering the credentials of a previously created user. There is an endpoint, called "test token" that allows you to verify that the authorization works correctly.

It is configured so that if the environment variable `STAGING` is set to `TRUE` all endpoints need authorization.

I have added the creation of a test user. To create it, enter the command `python -m src.init_db`

### CODE REVIEW

**Review by alvgonfri — COMMENTED** [review]
It looks fine, but I want to clarify some things before approving:
- The login works correclty when I log in from the "authorize" button, but when I tried to log in directly using the POST method, the test-token endpoint returned 401.
- I've tried to set STAGING to TRUE, but the endpoints didn't need authorization.

**Comment by gonzcm** [comment]
- When logging in from the login endpoint, the system returns the authorization and refresh tokens for the frontend to store and send along with the user's requests. When trying to make the request from Swagger it is normal that it does not work. To test from Swagger, the only way to do it is to login from authorize, this way, Swagger sends the tokens in each request.

- The environment variables do not seem to work correctly in some cases and this is something that needs to be addressed for the future. It seems that boolean variables remain with a static value and even if you change it, it still shows the same value as before. If you change the variable name in the environment file and consequently in the configuration files it should work correctly.

**Review by alvgonfri — APPROVED** [review]
Everything is clear now.

**Review by alvarobernal2412 — APPROVED** [review]
Well done! Auth module ready

**Pull request merged**
