### PR TITLE
Feature/3 api call for patient listing

### PR DESCRIPTION
**Pull request by josgarber6**
## Description
The objective of this feature is to implement the listing of the patients that will be used this week in the development of the application.

## Related Issue(s)
- #3 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @jmartinacu 
- @alvgonfri  

## Tester
- @gonzcm

### CODE REVIEW

**Review by alvgonfri — CHANGES_REQUESTED** [review]
The following error appears when I run `pytest`:

image

Also, the URL must be changed from `cyc/patient/list` to `cyc/patient`

**Comment by josgarber6** [comment]
The errors that appear when you run pytest, I have tried to solve them before pushing the changes but I wasn't able to fix them. I'm changing the URL right now.

**Review by alvgonfri — DISMISSED** [review]
Everything is working now, brilliant job!

This PR can be merged once the conflicts are resolved.

**Review by alvgonfri — APPROVED** [review]

**Review by alvarobernal2412 — APPROVED** [review]
Good job! Finally this PR can be merged

**Pull request merged**
