### PR TITLE
Conf/35 development workflows

### PR DESCRIPTION
**Pull request by gonzcm**
## Description
Added workflows for reviewing and formatting, and testing and generating coverage reports.

## Related Issue(s)
- #35 

## Checklist
- [x] I have read and followed the project's contributing guidelines.
- [x] I have tested the changes locally.
- [x] I have made corresponding changes to the documentation if necessary.
- [x] My code follows the project's code style guidelines.

## Reviewers
- @jmartinacu 
- @josgarber6 

## Notes
In order to run the testing workflow, the PR must be labeled as 'ready'.

### CODE REVIEW

**Review by josgarber6 — DISMISSED** [review]
Amazing job mate!

**Review by alvarobernal2412 — DISMISSED** [review]
In workflow you need read/write permissions, for this you can see how to do it [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions).

**Comment by gonzcm** [comment]
El problema no estaba relacionado con otorgar permisos epecíficos al workflow, sino activar la opción de que workflows para crear pull request desde la configuración de la organización.

**Review by alvarobernal2412 — APPROVED** [review]
Now workflows have write permissions!

**Pull request merged**
